[theme]
base = "dark"
primaryColor = "#7c3aed"
backgroundColor = "#12121e"
secondaryBackgroundColor = "#1e1e2e"
textColor = "#f0f0f0"

[server]
maxUploadSize = 800
maxMessageSize = 800
enableStaticServing = true

[global]
disableWidgetStateDuplicationWarning = true

[browser]
gatherUsageStats = true
